### ISSUE TITLE
Hmm. Can't call next

### ISSUE THREAD

**Issue by apanzerj** [htilly/zenmusic#23]
Getting this message:

```
Received: message #music-admin @panzer 1497566138.060215 "next"
term next
Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Next"
    at Request._callback (/opt/zenmusic/node_modules/sonos/lib/sonos.js:153:23)
    at Request.self.callback (/opt/zenmusic/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/opt/zenmusic/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/opt/zenmusic/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by apanzerj** [comment]
Wait...

**Comment by apanzerj** [comment]
Nope. Still not working.

**Comment by apanzerj** [comment]
I can't call next. I get the above error. Same versions as the ones in #19

**Comment by htilly** [comment]
But everything else is working?

**Comment by apanzerj** [comment]
Nope. Pause doesn't work either:

```
term pause
[ Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Pause"
      at Request._callback (/opt/zenmusic/node_modules/sonos/lib/sonos.js:153:23)
      at Request.self.callback (/opt/zenmusic/node_modules/request/request.js:188:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:194:7)
      at Request.<anonymous> (/opt/zenmusic/node_modules/request/request.js:1171:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:191:7)
      at IncomingMessage.<anonymous> (/opt/zenmusic/node_modules/request/request.js:1091:12)
      at Object.onceWrapper (events.js:293:19)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:188:7)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9),
  undefined ]
```

**Comment by apanzerj** [comment]
Stop gives me:
```
Received: message #music-admin @panzer 1497567263.267959 "stop"
term stop
[ null, true ]
```

**Comment by apanzerj** [comment]
Hmm. Add works. 

I get this when I added busines time:
```
Received: message #music-admin @panzer 1497567300.274915 "play"
term play
[ null, true ]
Received: message #music-admin @panzer 1497567316.277751 "add business time"
term add
{ tracks:
   { href: 'https://api.spotify.com/v1/search?query=business+time&type=track&market=US&offset=0&limit=1',
     items: [ [Object] ],
     limit: 1,
     next: 'https://api.spotify.com/v1/search?query=business+time&type=track&market=US&offset=1&limit=1',
     offset: 0,
     previous: null,
     total: 410 } }
queueLength [ '51' ]
Received: message #music-admin UNKNOWN_USER 1497567324.279217 "undefined"
Could not respond. text was undefined.
```
