### ISSUE TITLE
Error parsing DIDTL result

### ISSUE THREAD

**Issue by msil** [htilly/zenmusic#25]
Zenmusic seemed to be working for me a few days ago, just today i recived this error when attempting to list the current queue:
```
Starting...
Received: message #sonos @micky 1507128096.000512 "current"
term current
{ position: NaN,
  duration: NaN,
  uri: 'x-rincon:RINCON_B8E937D3DD6001400' }
Received: message #sonos @micky 1507128104.000015 "list"
term list
Error: Cannot parse DIDTL result
    at /home/micky/zen/zenmusic/node_modules/sonos/lib/sonos.js:1143:25
    at Parser.<anonymous> (/home/micky/zen/zenmusic/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at SAXParser.onclosetag (/home/micky/zen/zenmusic/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/micky/zen/zenmusic/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/micky/zen/zenmusic/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/micky/zen/zenmusic/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/micky/zen/zenmusic/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/micky/zen/zenmusic/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/home/micky/zen/zenmusic/node_modules/xml2js/lib/xml2js.js:7:59)
    at /home/micky/zen/zenmusic/node_modules/sonos/lib/sonos.js:1135:34
    at /home/micky/zen/zenmusic/node_modules/sonos/lib/services/Service.js:67:14
    at Parser.<anonymous> (/home/micky/zen/zenmusic/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
```

**Comment by htilly** [comment]
Hi!

What solved the issue ?

/Tilly
