### ISSUE TITLE
Receiving error when trying to start index.js

### ISSUE THREAD

**Issue by Goldbytes** [htilly/zenmusic#30]
[note, running on a Mac]

    throw err;
    ^

Error: Cannot find module 'urllib-sync'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/opt/zenmusic/index.js:1:80)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by htilly** [comment]
Hi!

Have you tried:
npm install urllib-sync --save

BR
Tilly

**Comment by htilly** [comment]
Closing case
