### ISSUE TITLE
Getting an error after following install instructions and running node index.js

### ISSUE THREAD

**Issue by CaptainAweesome** [htilly/zenmusic#38]
Note that I am running this on a VM without access to a sonos speaker at the moment.

Terminal output:

/opt/zenmusic/node_modules/sonos/lib/sonos.js:66
  var implicitListen = async function (event, listener) {
                             ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/zenmusic/node_modules/sonos/index.js:1:80)

config.json:

{
    "adminChannel" : "spotify",
    "standardChannel" : "spotify",
    "gongLimit": 3,
    "voteLimit": 6,
    "sonos" : "",
    "token" : "xoxb...",
    "market" : "US",
    "maxVolume" : 75,
    "blacklist" : "@justin.bieber, @one.direction",
    "apiKey": "abc...:abc..."
}

**Comment by CaptainAweesome** [comment]
Node.js v6.11.2

I get this error when entering "node index.js" directly in the bash terminal. 

captainaweesome:/opt/zenmusic (master) $ node index.js

**Comment by htilly** [comment]
U need to be running Node 7.5 or above!
Try upgrading node and give it another go!

**Comment by htilly** [comment]
Also, your API code for Spotify might be wrong. Obviously you didn't type the whole code :-) , but there should not be any : in there.. 
Make sure you encoded it with base64 as described in the README.

**Comment by CaptainAweesome** [comment]
Seems to work after upgrading to Node v8.11.3 "nvm install 8.11.3" and removing ":" from spotify apikey.
Getting an Error when not connected to sonos speaker but it's likely due to the fact there's no speaker.
Now for the realworld testing with a Pi and speaker. To be continued..


07-11 13:04:01:786   Received: message undefined <@UBPNEEC1L> 1531314241.000284 "list"
07-11 13:04:01:786   term list
07-11 13:04:01:788   Current queue:  false
07-11 13:04:01:789   Error occurred %j { RequestError: Error: connect ECONNREFUSED 0.0.0.0:1400
    at new RequestError (/opt/zenmusic/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/zenmusic/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/zenmusic/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/zenmusic/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/opt/zenmusic/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 0.0.0.0:1400',
  cause: 
   { Error: connect ECONNREFUSED 0.0.0.0:1400
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '0.0.0.0',
     port: 1400 },
  error: 
   { Error: connect ECONNREFUSED 0.0.0.0:1400
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '0.0.0.0',
     port: 1400 },
  options: 
   { uri: 'http://0.0.0.0:1400/MediaRenderer/AVTransport/Control',
     method: 'POST',
     headers: 
      { SOAPAction: '"urn:schemas-upnp-org:service:AVTransport:1#GetTransportInfo"',
        'Content-type': 'text/xml; charset=utf8' },
     body: '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetTransportInfo xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID></u:GetTransportInfo></s:Body></s:Envelope>',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
07-11 13:04:01:790   Error occurred %j { RequestError: Error: connect ECONNREFUSED 0.0.0.0:1400
    at new RequestError (/opt/zenmusic/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/zenmusic/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/zenmusic/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/zenmusic/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/opt/zenmusic/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 0.0.0.0:1400',
  cause: 
   { Error: connect ECONNREFUSED 0.0.0.0:1400
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '0.0.0.0',
     port: 1400 },
  error: 
   { Error: connect ECONNREFUSED 0.0.0.0:1400
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '0.0.0.0',
     port: 1400 },
  options: 
   { uri: 'http://0.0.0.0:1400/MediaRenderer/AVTransport/Control',
     method: 'POST',
     headers: 
      { SOAPAction: '"urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo"',
        'Content-type': 'text/xml; charset=utf8' },
     body: '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetPositionInfo xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID></u:GetPositionInfo></s:Body></s:Envelope>',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

**Comment by htilly** [comment]
Good news! To verify your spotify account, simply try the "search" function. Should work without connection to the Sonos.

**Comment by CaptainAweesome** [comment]
Spotify for developers dashboard says: 
**No data available.
Check back when you've made some
requests using this app for data.**

which means it's not getting any requests from the bot

**Comment by CaptainAweesome** [comment]
Thank you very much for the quick reply and easy fix! It seems to search for songs without problems
But maybe it could have been explained in the instructions, step-by-step. :)
